# Generated by Django 5.2.5 on 2025-08-16 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_remove_order_paymentid_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='delivery_time_minutes',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='medicine',
            name='is_delivery_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='is_emergency_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicine',
            name='is_marketplace_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='storage_temperature',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
