# Generated by Django 5.2.5 on 2025-08-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacy", "0005_medicine_delivery_time_minutes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pharmacist",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
