# Generated by Django 5.2.5 on 2025-08-16 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0006_alter_pharmacist_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyShop',
            fields=[
                ('shop_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('license_number', models.CharField(max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('delivery_available', models.BooleanField(default=True)),
                ('delivery_radius', models.IntegerField(default=10)),
                ('average_delivery_time', models.IntegerField(default=60)),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('total_reviews', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='medicine',
            name='generic_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='pharmacy_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.pharmacyshop'),
        ),
        migrations.CreateModel(
            name='MedicinePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.medicine')),
                ('pharmacy_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.pharmacyshop')),
            ],
            options={
                'unique_together': {('medicine', 'pharmacy_shop')},
            },
        ),
    ]
