# Generated by Django 5.2.5 on 2025-08-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital_admin", "0005_admin_information_hospital"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admin_information",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="clinical_laboratory_technician",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
