# Generated by Django 5.2.5 on 2025-08-15 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0005_user_is_verified"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_verified",
        ),
    ]
