# Generated by Django 5.2.5 on 2025-08-15 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0006_remove_user_is_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="otp_code",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="otp_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
