# Generated by Django 5.2.5 on 2025-08-16 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0008_user_account_locked_until_user_backup_codes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hospital_information",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="hospital_information",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
    ]
