# Generated by Django 5.2.5 on 2025-08-16 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0009_hospital_information_latitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_delivery_partner",
            field=models.BooleanField(default=False),
        ),
    ]
