# Generated by Django 5.2.5 on 2025-08-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0010_user_is_delivery_partner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hospital_information",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
