# Generated by Django 5.2.5 on 2025-08-16 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0044_appointment_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor_information",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="doctor_information",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
    ]
