# Generated by Django 5.2.5 on 2025-08-16 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0045_doctor_information_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_information',
            name='average_response_time',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='doctor_information',
            name='home_visit_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctor_information',
            name='home_visit_fee',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor_information',
            name='instant_booking_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctor_information',
            name='is_marketplace_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctor_information',
            name='marketplace_rating',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='doctor_information',
            name='online_consultation_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='doctor_information',
            name='online_consultation_fee',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor_information',
            name='service_radius',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='doctor_information',
            name='total_consultations',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctor_information',
            name='total_marketplace_reviews',
            field=models.IntegerField(default=0),
        ),
    ]
