# Generated by Django 5.2.5 on 2025-08-16 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0046_doctor_information_average_response_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription_medicine',
            name='is_ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prescription_medicine',
            name='order_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ordered', 'Ordered'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='prescription_medicine',
            name='ordered_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
